[package]
name = "analytics-next"
version = "0.1.0"
edition = "2021"

[dependencies]
gloo-utils = "0.1"
js-sys = "0.3.64"
serde = { version = "1", features = ["derive" ] }
serde_json = "1"
wasm-bindgen = "0.2.87"

analytics-next-sys = { path = "analytics-next-sys" }

[dependencies.web-sys]
version = "0.3"

[package.metadata.docs.rs]
all-features = true
